version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      # - prometheus_data:/prometheus
    ports:
    - 9090:9090
    # command:
    # - '--config.file=prometheus/config.yml'